### ISSUE TITLE
Update the README to refer people to mesos/spark-ec2

### ISSUE THREAD

**Issue by nchammas** [shivaram/spark-ec2#5]
Example: https://issues.apache.org/jira/browse/SPARK-5298?focusedCommentId=14281564&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14281564

A small number of people are thrown off by the fact that `mesos/spark-ec2` is a fork of this repo, so they think this is the primary repo.

I suggest updating the README somehow to direct people appropriately.

**Comment by shivaram** [comment]
I added a note to the README as you can see in https://github.com/shivaram/spark-ec2/blob/master/README.md

**Comment by nchammas** [comment]
Looks good to me.
